version: '3.1'
services:
    mongo_db:
        image: mongo
        ports:
            - '27017:27017'
    api:
        environment:
            PORT: 3000
            MONGO_URL: mongo_db
            MONGO_PORT: 27017
        ports:
            - 3000:3000 #Remove this
            - 3001:3001
            - '5858:5858'
        build:
            context: .
        restart: always
        depends_on:
            - mongo_db #Remove this
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached #Remove this
        logging:
            options:
                max-size: '10m'
                max-file: '10'
        command: yarn run dev
