version: '3.1'
services:
    mongo_db:
        image: mongo
        ports:
            - '27017:27017'
    api:
        ports:
            - 3000:3000
            - 3001:3001
            - '5858:5858'
        build:
            context: .
        restart: always
        depends_on:
            - mongo_db
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached
        logging:
            options:
                max-size: '10m'
                max-file: '10'
        command: yarn run dev
