version: '3.1'
services:
    api:
        build:
            context: docker
        restart: always
        working_dir: var/www
        logging:
            options:
                max-size: '10m'
                max-file: '10'
        command: yarn run dev
