version: 2
jobs:
    build:
        docker:
            - image: circleci/node:9.11.2
        steps:
            - checkout
            # Try to install using cache
            - restore_cache:
                  keys:
                      # Find a cache corresponding to this specific yarn.lock checksum
                      # when this file is changed, this key will fail
                      - v1-npm-deps-{{ checksum "yarn.lock" }}
                      # Find the most recently generated cache used from any branch
                      - v1-npm-deps-
            - run: yarn
            - save_cache:
                  key: v1-npm-deps-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
    test:
        docker:
            - image: circleci/node:9.11.2
        steps:
            - checkout
            - restore_cache:
                  keys:
                      # Find a cache corresponding to this specific yarn.lock checksum
                      # when this file is changed, this key will fail
                      - v1-npm-deps-{{ checksum "yarn.lock" }}
                      # Find the most recently generated cache used from any branch
                      - v1-npm-deps-
            - run: yarn install
            - run: yarn test
workflows:
    version: 2
    build_test_deploy:
        jobs:
            - build
            - test:
                  requires:
                      - build
